[customizations.installer.kickstart]
contents = """
rootpw --lock
network --bootproto=dhcp --device=link --activate
keyboard --vckeymap=fi --xlayouts='fi'
timezone Europe/Helsinki
%post
bootc switch --mutate-in-place --transport registry ghcr.io/s33po/bootc-centos:test2
rm -f /var/lib/systemd/random-seed
rm -f /etc/machine-id
truncate -s 0 /etc/machine-id
%end
"""

[customizations.installer.modules]
enable = [
  "org.fedoraproject.Anaconda.Modules.Localization",
  "org.fedoraproject.Anaconda.Modules.Network",
  "org.fedoraproject.Anaconda.Modules.Runtime",
  "org.fedoraproject.Anaconda.Modules.Security",
  "org.fedoraproject.Anaconda.Modules.Services",
  "org.fedoraproject.Anaconda.Modules.Storage",
  "org.fedoraproject.Anaconda.Modules.Timezone",
  "org.fedoraproject.Anaconda.Modules.Users"
]
disable = [
  "org.fedoraproject.Anaconda.Modules.Subscription"
]
